name: rsv-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake-minimal>=7.32
  - fastqc=0.11.9
  - trimmomatic=0.39
  - bwa>=0.7.17
  - samtools>=1.16
  - bcftools>=1.16
  - picard>=3.0
  - mafft>=7.520
  - iqtree=2.2.0
  - biopython>=1.83
  - multiqc>=1.15
